# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
  - cron: "15 11 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: download pic
      run: |
        python3 pixiv.py "https://www.pixiv.net/ranking.php?mode=male"
    - name: upload tg
      run: |
        TOKEN=1197345943:AAF-ZoDQyubKBihGniH81hzcp63KpKdnUqE	
        chat_ID=-1001669405259
        for i in PixivImage/*
        do   
        curl -F chat_id=$chat_ID -F photo=@"$i" https://api.telegram.org/bot$TOKEN/sendPhoto
        curl -F chat_id=$chat_ID -F document=@"$i" https://api.telegram.org/bot$TOKEN/sendDocument
        rm -rf $i
        done
